// AUTOGENERATED CODE on 2026-08-06T16:27:35.628774 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(directled_bio_code, BM_DIRECTLED_BIO_START, BM_DIRECTLED_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	21f",
    // --- inline asm end ---
    "21:", // main: @main
    "addi	sp, sp, -96",
    "sw	ra, 92(sp)", // 4-byte Folded Spill
    "sw	s0, 88(sp)", // 4-byte Folded Spill
    "sw	s1, 84(sp)", // 4-byte Folded Spill
    "li	a0, 0",
    "lui	s1, %hi(124f)",
    "addi	s1, s1, %lo(124f)",
    "li	a1, -1",
    "sb	a1, 308(s1)",
    // --- inline asm begin ---
    "mv	x27, a0",
    // --- inline asm end ---
    "lw	a0, 320(s1)",
    "lui	s0, 1",
    "lui	a1, 271171",
    "addi	a1, a1, 836",
    "addi	a2, s0, -1",
    "sw	a2, 4(sp)", // 4-byte Folded Spill
    "bne	a0, a1, 24f",
    "lw	a0, 324(s1)",
    "lui	a1, 202053",
    "addi	a1, a1, -177",
    "bne	a0, a1, 24f",
    "lw	a0, 328(s1)",
    "lui	a1, 16",
    "addi	a1, a1, 30",
    "bne	a0, a1, 24f",
    "lw	a0, 332(s1)",
    "lui	a1, 678964",
    "addi	a1, a1, -859",
    "bne	a0, a1, 24f",
    "lw	a0, 460(s1)",
    // ERRATA BUG2 patch: lui	a1, 136261 (B2:bits24:20=20)
    "lui a1, 0x20045",
    "sw t0, -4(sp)",
    "addi t0, zero, 5",
    "slli t0, t0, 10",
    "slli t0, t0, 12",
    "add a1, a1, t0",
    "lw t0, -4(sp)",
    "addi	a1, a1, -443",
    "bne	a0, a1, 24f",
    "li	a1, 0",
    "lw	a0, 456(s1)",
    "li	a2, -1",
    // ERRATA BUG1 patch: lui	a3, 973704 (B1:phantom-rs1)
    "lui a3, 0xedb00",
    "sw t0, -4(sp)",
    "addi t0, zero, 17",
    "slli t0, t0, 3",
    "slli t0, t0, 12",
    "add a3, a3, t0",
    "lw t0, -4(sp)",
    "addi	a3, a3, 800",
    "li	a4, 128",
    "22:", // .LBB1_6: =>This Loop Header: Depth=1
    // Child Loop BB1_7 Depth 2
    "add	a5, s1, a1",
    "lbu	a5, 328(a5)",
    "xor	a2, a2, a5",
    "li	a5, 8",
    "23:", // .LBB1_7: Parent Loop BB1_6 Depth=1
    // =>  This Inner Loop Header: Depth=2
    "srli	s1, a2, 1",
    "slli	a2, a2, 31",
    "srai	a2, a2, 31",
    "and	a2, a2, a3",
    "addi	a5, a5, -1",
    "xor	a2, a2, s1",
    "bnez	a5, 23b",
    // in Loop: Header=BB1_6 Depth=1
    "addi	a1, a1, 1",
    "lui	s1, %hi(124f)",
    "addi	s1, s1, %lo(124f)",
    "bne	a1, a4, 22b",
    "xor	a0, a0, a2",
    "li	a1, -1",
    "beq	a0, a1, 104f",
    "24:", // .LBB1_10
    "sw	zero, 40(sp)", // 4-byte Folded Spill
    "lui	a0, 262144",
    "lui	a1, 4",
    "lui	a2, 1048568",
    "addi	a3, s0, -1296",
    "sw	a3, 16(sp)", // 4-byte Folded Spill
    "lui	a3, 901953",
    "addi	a0, a0, -64",
    "sw	a0, 12(sp)", // 4-byte Folded Spill
    "addi	a0, a1, -1384",
    "sw	a0, 28(sp)", // 4-byte Folded Spill
    "addi	a2, a2, -1",
    "sw	a2, 0(sp)", // 4-byte Folded Spill
    "addi	a3, a3, -16",
    "sw	a3, 36(sp)", // 4-byte Folded Spill
    "lui	a0, 901965",
    "lui	a1, 901966",
    "addi	a5, a0, 718",
    "addi	a0, a1, 256",
    "sw	a0, 24(sp)", // 4-byte Folded Spill
    "sw	a5, 32(sp)", // 4-byte Folded Spill
    "25:", // .LBB1_11: =>This Loop Header: Depth=1
    // Child Loop BB1_53 Depth 2
    // Child Loop BB1_58 Depth 3
    // Child Loop BB1_130 Depth 2
    // Child Loop BB1_147 Depth 3
    // Child Loop BB1_156 Depth 2
    // Child Loop BB1_158 Depth 3
    // Child Loop BB1_114 Depth 2
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "bgez	a0, 69f",
    "j	42f",
    "26:", // .LBB1_12: in Loop: Header=BB1_53 Depth=2
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "andi	a1, a1, 240",
    "li	a2, 208",
    "beq	a1, a2, 58f",
    // in Loop: Header=BB1_53 Depth=2
    "li	a1, 32",
    "bltu	a0, a1, 27f",
    // in Loop: Header=BB1_53 Depth=2
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "li	a1, 61",
    "bltu	a1, a0, 27f",
    // in Loop: Header=BB1_53 Depth=2
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "addi	a1, a0, -32",
    "li	a2, 9",
    "bltu	a2, a1, 32f",
    // in Loop: Header=BB1_53 Depth=2
    "srli	a0, s0, 24",
    "bnez	a0, 41f",
    // in Loop: Header=BB1_53 Depth=2
    "slli	a1, a1, 2",
    "add	a1, a1, s1",
    "sw	s0, 40(a1)",
    "j	40f",
    "27:", // .LBB1_18: in Loop: Header=BB1_53 Depth=2
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "li	a1, 9",
    "bltu	a1, a0, 28f",
    // in Loop: Header=BB1_53 Depth=2
    "srli	a0, s0, 24",
    "bnez	a0, 66f",
    // in Loop: Header=BB1_53 Depth=2
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "addi	a1, a0, 1",
    "slli	a0, a0, 2",
    "sb	a1, 308(s1)",
    "add	a0, a0, s1",
    "sw	s0, 40(a0)",
    "j	68f",
    "28:", // .LBB1_21: in Loop: Header=BB1_53 Depth=2
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "li	a1, 19",
    "bltu	a1, a0, 31f",
    // in Loop: Header=BB1_53 Depth=2
    "srli	a1, s0, 8",
    // ERRATA BUG2 patch: srli	a0, s0, 20 (shamt=20)
    "srli a0, s0, 19",
    "srli a0, a0, 1",
    "and	a1, a1, a3",
    "bnez	a0, 29f",
    // in Loop: Header=BB1_53 Depth=2
    "beqz	a1, 30f",
    "29:", // .LBB1_24: in Loop: Header=BB1_53 Depth=2
    "beqz	a1, 66f",
    // in Loop: Header=BB1_53 Depth=2
    "bltu	a1, a0, 66f",
    "30:", // .LBB1_26: in Loop: Header=BB1_53 Depth=2
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "slli	a0, a0, 2",
    "add	a0, a0, s1",
    "sw	s0, 80(a0)",
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "addi	a0, a0, 1",
    "sb	a0, 308(s1)",
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "li	a1, 20",
    "bne	a0, a1, 68f",
    // in Loop: Header=BB1_53 Depth=2
    "jal	ra, 117f",
    "j	45f",
    "31:", // .LBB1_28: in Loop: Header=BB1_53 Depth=2
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "li	a1, 29",
    "bltu	a1, a0, 68f",
    // in Loop: Header=BB1_53 Depth=2
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "addi	a0, a0, -20",
    "slli	a0, a0, 2",
    "add	a0, a0, s1",
    "lw	a1, 120(a0)",
    "srli	a2, s0, 13",
    "bnez	a2, 66f",
    // in Loop: Header=BB1_53 Depth=2
    "srli	a2, a1, 8",
    "srli	a3, s0, 12",
    "lw	a4, 4(sp)", // 4-byte Folded Reload
    "and	a2, a2, a4",
    "bnez	a3, 36f",
    // in Loop: Header=BB1_53 Depth=2
    "and	a1, s0, a4",
    "beqz	a1, 37f",
    // in Loop: Header=BB1_53 Depth=2
    "bnez	a2, 37f",
    "j	66f",
    "32:", // .LBB1_33: in Loop: Header=BB1_53 Depth=2
    "li	a2, 19",
    "bltu	a2, a1, 35f",
    // in Loop: Header=BB1_53 Depth=2
    "srli	a2, s0, 8",
    // ERRATA BUG2 patch: srli	a1, s0, 20 (shamt=20)
    "srli a1, s0, 19",
    "srli a1, a1, 1",
    "and	a2, a2, a3",
    "bnez	a1, 33f",
    // in Loop: Header=BB1_53 Depth=2
    "beqz	a2, 34f",
    "33:", // .LBB1_36: in Loop: Header=BB1_53 Depth=2
    "beqz	a2, 41f",
    // in Loop: Header=BB1_53 Depth=2
    "bltu	a2, a1, 41f",
    "34:", // .LBB1_38: in Loop: Header=BB1_53 Depth=2
    "slli	a0, a0, 2",
    "add	a0, a0, s1",
    "sw	s0, -48(a0)",
    "j	40f",
    "35:", // .LBB1_39: in Loop: Header=BB1_53 Depth=2
    "addi	a0, a0, -52",
    "slli	a0, a0, 2",
    "add	a0, a0, s1",
    "lw	a1, 120(a0)",
    "srli	a2, s0, 13",
    "bnez	a2, 41f",
    // in Loop: Header=BB1_53 Depth=2
    "srli	a2, a1, 8",
    "srli	a3, s0, 12",
    "lw	a4, 4(sp)", // 4-byte Folded Reload
    "and	a2, a2, a4",
    "bnez	a3, 38f",
    // in Loop: Header=BB1_53 Depth=2
    "and	a1, s0, a4",
    "beqz	a1, 39f",
    // in Loop: Header=BB1_53 Depth=2
    "bnez	a2, 39f",
    "j	41f",
    "36:", // .LBB1_43: in Loop: Header=BB1_53 Depth=2
    "li	a3, 50",
    "bltu	a2, a3, 66f",
    // in Loop: Header=BB1_53 Depth=2
    // ERRATA BUG2 patch: srli	a1, a1, 20 (shamt=20)
    "srli a1, a1, 19",
    "srli a1, a1, 1",
    "bne	a1, a2, 66f",
    "37:", // .LBB1_45: in Loop: Header=BB1_53 Depth=2
    "sw	s0, 200(a0)",
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "addi	a0, a0, 1",
    "sb	a0, 308(s1)",
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "li	a1, 30",
    "bne	a0, a1, 68f",
    // in Loop: Header=BB1_53 Depth=2
    "jal	ra, 117f",
    "j	65f",
    "38:", // .LBB1_47: in Loop: Header=BB1_53 Depth=2
    "li	a3, 50",
    "bltu	a2, a3, 41f",
    // in Loop: Header=BB1_53 Depth=2
    // ERRATA BUG2 patch: srli	a1, a1, 20 (shamt=20)
    "srli a1, a1, 19",
    "srli a1, a1, 1",
    "bne	a1, a2, 41f",
    "39:", // .LBB1_49: in Loop: Header=BB1_53 Depth=2
    "sw	s0, 200(a0)",
    "40:", // .LBB1_50: in Loop: Header=BB1_53 Depth=2
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "addi	a0, a0, 1",
    "sb	a0, 308(s1)",
    "lw	a0, 28(sp)", // 4-byte Folded Reload
    "sh	a0, 314(s1)",
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "li	a1, 62",
    "bne	a0, a1, 68f",
    // in Loop: Header=BB1_53 Depth=2
    "jal	ra, 117f",
    "lw	a5, 32(sp)", // 4-byte Folded Reload
    "li	a0, -1",
    "sb	a0, 308(s1)",
    "lw	a0, 40(sp)", // 4-byte Folded Reload
    "j	50f",
    "41:", // .LBB1_52: in Loop: Header=BB1_53 Depth=2
    "jal	ra, 111f",
    "j	45f",
    "42:", // .LBB1_53: Parent Loop BB1_11 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB1_58 Depth 3
    // --- inline asm begin ---
    "mv	s0, x19",
    // --- inline asm end ---
    "beq	s0, a5, 46f",
    // in Loop: Header=BB1_53 Depth=2
    "lui	a0, 901965",
    "addi	a0, a0, 462",
    "beq	s0, a0, 43f",
    // in Loop: Header=BB1_53 Depth=2
    "lw	a0, 36(sp)", // 4-byte Folded Reload
    "bne	s0, a0, 51f",
    // in Loop: Header=BB1_53 Depth=2
    "li	a0, -1",
    "sb	a0, 308(s1)",
    "lw	a0, 40(sp)", // 4-byte Folded Reload
    "sh	a0, 314(s1)",
    "sh	a0, 316(s1)",
    "sb	a0, 309(s1)",
    // --- inline asm begin ---
    "mv	x26, a0",
    // --- inline asm end ---
    "j	68f",
    "43:", // .LBB1_57: in Loop: Header=BB1_53 Depth=2
    "jal	ra, 111f",
    "addi	a0, s1, 200",
    "44:", // .LBB1_58: Parent Loop BB1_11 Depth=1
    // Parent Loop BB1_53 Depth=2
    // =>    This Inner Loop Header: Depth=3
    "sw	zero, 0(a0)",
    "addi	a0, a0, 4",
    "addi	a1, s1, 240",
    "bne	a0, a1, 44b",
    // in Loop: Header=BB1_53 Depth=2
    "lw	a0, 40(sp)", // 4-byte Folded Reload
    "sb	a0, 308(s1)",
    "45:", // .LBB1_60: in Loop: Header=BB1_53 Depth=2
    "lw	a5, 32(sp)", // 4-byte Folded Reload
    "j	68f",
    "46:", // .LBB1_61: in Loop: Header=BB1_53 Depth=2
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "li	a1, 32",
    "bltu	a0, a1, 47f",
    // in Loop: Header=BB1_53 Depth=2
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "li	a1, 62",
    "bltu	a0, a1, 48f",
    "47:", // .LBB1_63: in Loop: Header=BB1_53 Depth=2
    "lbu	a0, 309(s1)",
    "sb	a0, 313(s1)",
    "48:", // .LBB1_64: in Loop: Header=BB1_53 Depth=2
    "li	a0, 32",
    "sb	a0, 308(s1)",
    "li	a0, 1",
    "sb	a0, 309(s1)",
    "lbu	a0, 313(s1)",
    "bnez	a0, 49f",
    // in Loop: Header=BB1_53 Depth=2
    "li	a0, 100",
    "sb	a0, 310(s1)",
    "49:", // .LBB1_66: in Loop: Header=BB1_53 Depth=2
    "lw	a0, 40(sp)", // 4-byte Folded Reload
    "sb	a0, 311(s1)",
    "sb	a0, 312(s1)",
    "lw	a0, 28(sp)", // 4-byte Folded Reload
    "50:", // .LBB1_67: in Loop: Header=BB1_53 Depth=2
    "sh	a0, 314(s1)",
    "j	68f",
    "51:", // .LBB1_68: in Loop: Header=BB1_53 Depth=2
    "andi	a1, s0, -16",
    "andi	a0, s0, 14",
    "lw	a2, 24(sp)", // 4-byte Folded Reload
    "bne	a1, a2, 52f",
    // in Loop: Header=BB1_53 Depth=2
    "li	a2, 9",
    "bltu	a2, a0, 52f",
    // in Loop: Header=BB1_53 Depth=2
    "jal	ra, 111f",
    "lw	a5, 32(sp)", // 4-byte Folded Reload
    "ori	a0, s0, 128",
    "j	67f",
    "52:", // .LBB1_71: in Loop: Header=BB1_53 Depth=2
    "lui	a2, 901966",
    "addi	a2, a2, 512",
    "bne	a1, a2, 53f",
    // in Loop: Header=BB1_53 Depth=2
    "li	a1, 9",
    "bltu	a1, a0, 53f",
    // in Loop: Header=BB1_53 Depth=2
    "jal	ra, 111f",
    "lw	a5, 32(sp)", // 4-byte Folded Reload
    "ori	a0, s0, 176",
    "j	67f",
    "53:", // .LBB1_74: in Loop: Header=BB1_53 Depth=2
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "li	a1, 255",
    "beq	a0, a1, 68f",
    // in Loop: Header=BB1_53 Depth=2
    // ERRATA BUG2 patch: lb	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lb a0, 312(s1)",
    "addi s1, s1, 4",
    "li	a1, -113",
    "blt	a1, a0, 54f",
    // in Loop: Header=BB1_53 Depth=2
    "srli	a0, s0, 24",
    "bnez	a0, 66f",
    // in Loop: Header=BB1_53 Depth=2
    "sw	s0, 300(s1)",
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "andi	a0, a0, 15",
    "addi	a0, a0, 144",
    "j	67f",
    "54:", // .LBB1_78: in Loop: Header=BB1_53 Depth=2
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    // ERRATA BUG2 patch: lbu	a1, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a1, 312(s1)",
    "addi s1, s1, 4",
    "andi	a0, a0, 240",
    "lw	a3, 4(sp)", // 4-byte Folded Reload
    "li	a2, 144",
    "bne	a0, a2, 57f",
    // in Loop: Header=BB1_53 Depth=2
    "srli	a2, s0, 8",
    // ERRATA BUG2 patch: srli	a0, s0, 20 (shamt=20)
    "srli a0, s0, 19",
    "srli a0, a0, 1",
    "and	a2, a2, a3",
    "bnez	a0, 55f",
    // in Loop: Header=BB1_53 Depth=2
    "beqz	a2, 56f",
    "55:", // .LBB1_81: in Loop: Header=BB1_53 Depth=2
    "beqz	a2, 66f",
    // in Loop: Header=BB1_53 Depth=2
    "bltu	a2, a0, 66f",
    "56:", // .LBB1_83: in Loop: Header=BB1_53 Depth=2
    "andi	a0, a1, 15",
    "sw	s0, 304(s1)",
    "mv	s0, a0",
    "li	a1, 0",
    "jal	ra, 120f",
    "lw	a5, 32(sp)", // 4-byte Folded Reload
    "addi	a0, s0, 160",
    "j	67f",
    "57:", // .LBB1_84: in Loop: Header=BB1_53 Depth=2
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "andi	a1, a1, 240",
    "li	a2, 160",
    "bne	a1, a2, 59f",
    "58:", // .LBB1_85: in Loop: Header=BB1_53 Depth=2
    "lw	a1, 304(s1)",
    "srli	a2, s0, 13",
    "bnez	a2, 66f",
    // in Loop: Header=BB1_53 Depth=2
    "srli	a2, a1, 8",
    "srli	a3, s0, 12",
    "lw	a4, 4(sp)", // 4-byte Folded Reload
    "and	a2, a2, a4",
    "bnez	a3, 63f",
    // in Loop: Header=BB1_53 Depth=2
    "and	a1, s0, a4",
    "beqz	a1, 64f",
    // in Loop: Header=BB1_53 Depth=2
    "bnez	a2, 64f",
    "j	66f",
    "59:", // .LBB1_89: in Loop: Header=BB1_53 Depth=2
    "andi	a0, a0, 240",
    "li	a1, 176",
    "bne	a0, a1, 60f",
    // in Loop: Header=BB1_53 Depth=2
    "srli	a0, s0, 24",
    "bnez	a0, 66f",
    // in Loop: Header=BB1_53 Depth=2
    "sw	s0, 300(s1)",
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "andi	a0, a0, 15",
    "addi	a0, a0, 192",
    "j	67f",
    "60:", // .LBB1_92: in Loop: Header=BB1_53 Depth=2
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    // ERRATA BUG2 patch: lbu	a1, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a1, 312(s1)",
    "addi s1, s1, 4",
    "andi	a0, a0, 240",
    "li	a2, 192",
    "bne	a0, a2, 26b",
    // in Loop: Header=BB1_53 Depth=2
    "srli	a2, s0, 8",
    // ERRATA BUG2 patch: srli	a0, s0, 20 (shamt=20)
    "srli a0, s0, 19",
    "srli a0, a0, 1",
    "and	a2, a2, a3",
    "bnez	a0, 61f",
    // in Loop: Header=BB1_53 Depth=2
    "beqz	a2, 62f",
    "61:", // .LBB1_95: in Loop: Header=BB1_53 Depth=2
    "beqz	a2, 66f",
    // in Loop: Header=BB1_53 Depth=2
    "bltu	a2, a0, 66f",
    "62:", // .LBB1_97: in Loop: Header=BB1_53 Depth=2
    "andi	a1, a1, 15",
    "sw	s0, 304(s1)",
    "addi	a0, a1, 208",
    "j	67f",
    "63:", // .LBB1_98: in Loop: Header=BB1_53 Depth=2
    "li	a3, 50",
    "bltu	a2, a3, 66f",
    // in Loop: Header=BB1_53 Depth=2
    // ERRATA BUG2 patch: srli	a1, a1, 20 (shamt=20)
    "srli a1, a1, 19",
    "srli a1, a1, 1",
    "bne	a1, a2, 66f",
    "64:", // .LBB1_100: in Loop: Header=BB1_53 Depth=2
    "andi	a0, a0, 15",
    "mv	a1, s0",
    "jal	ra, 120f",
    "65:", // .LBB1_101: in Loop: Header=BB1_53 Depth=2
    "lw	a5, 32(sp)", // 4-byte Folded Reload
    "66:", // .LBB1_102: in Loop: Header=BB1_53 Depth=2
    "li	a0, -1",
    "67:", // .LBB1_103: in Loop: Header=BB1_53 Depth=2
    "sb	a0, 308(s1)",
    "68:", // .LBB1_104: in Loop: Header=BB1_53 Depth=2
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "bltz	a0, 42b",
    "69:", // .LBB1_105: in Loop: Header=BB1_11 Depth=1
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "li	a1, 32",
    "bltu	a0, a1, 71f",
    // in Loop: Header=BB1_11 Depth=1
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "li	a1, 61",
    "bltu	a1, a0, 71f",
    // in Loop: Header=BB1_11 Depth=1
    "lhu	a0, 314(s1)",
    "beqz	a0, 70f",
    // in Loop: Header=BB1_11 Depth=1
    "lh	a0, 314(s1)",
    "addi	a0, a0, -1",
    "sh	a0, 314(s1)",
    "70:", // .LBB1_109: in Loop: Header=BB1_11 Depth=1
    "lhu	a0, 314(s1)",
    "bnez	a0, 71f",
    // in Loop: Header=BB1_11 Depth=1
    "jal	ra, 111f",
    "lw	a5, 32(sp)", // 4-byte Folded Reload
    "71:", // .LBB1_111: in Loop: Header=BB1_11 Depth=1
    "lhu	a0, 316(s1)",
    "beqz	a0, 74f",
    // in Loop: Header=BB1_11 Depth=1
    "lh	a0, 316(s1)",
    "addi	a0, a0, -1",
    "sh	a0, 316(s1)",
    "72:", // .LBB1_113: in Loop: Header=BB1_11 Depth=1
    "lw	a0, 16(sp)", // 4-byte Folded Reload
    "73:", // .LBB1_114: Parent Loop BB1_11 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a0, a0, -1",
    "bnez	a0, 73b",
    "j	25b",
    "74:", // .LBB1_115: in Loop: Header=BB1_11 Depth=1
    "lbu	a0, 309(s1)",
    "beqz	a0, 72b",
    // in Loop: Header=BB1_11 Depth=1
    "lbu	a0, 311(s1)",
    "bnez	a0, 75f",
    // in Loop: Header=BB1_11 Depth=1
    "lui	a0, 524288",
    // --- inline asm begin ---
    "mv	x17, a0",
    // --- inline asm end ---
    "li	a0, 70",
    "sb	a0, 311(s1)",
    "75:", // .LBB1_118: in Loop: Header=BB1_11 Depth=1
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a0, x31",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a1, x31",
    // --- inline asm end ---
    "sub	a1, a1, a0",
    "lw	a0, 12(sp)", // 4-byte Folded Reload
    "and	a0, a0, a1",
    "snez	a0, a0",
    "addi	a0, a0, 1",
    "jal	ra, 114f",
    "lbu	a0, 310(s1)",
    "beqz	a0, 77f",
    // in Loop: Header=BB1_11 Depth=1
    "lbu	a0, 310(s1)",
    "addi	a0, a0, -1",
    "sb	a0, 310(s1)",
    "76:", // .LBB1_120: in Loop: Header=BB1_11 Depth=1
    "lw	a5, 32(sp)", // 4-byte Folded Reload
    "j	78f",
    "77:", // .LBB1_121: in Loop: Header=BB1_11 Depth=1
    "lbu	a0, 312(s1)",
    "lw	a5, 32(sp)", // 4-byte Folded Reload
    "beqz	a0, 80f",
    "78:", // .LBB1_122: in Loop: Header=BB1_11 Depth=1
    "lbu	a0, 311(s1)",
    "beqz	a0, 79f",
    // in Loop: Header=BB1_11 Depth=1
    "lbu	a0, 311(s1)",
    "addi	a0, a0, -1",
    "sb	a0, 311(s1)",
    "79:", // .LBB1_124: in Loop: Header=BB1_11 Depth=1
    "lbu	a0, 312(s1)",
    "beqz	a0, 72b",
    // in Loop: Header=BB1_11 Depth=1
    "lbu	a0, 312(s1)",
    "addi	a0, a0, -1",
    "sb	a0, 312(s1)",
    "j	72b",
    "80:", // .LBB1_126: in Loop: Header=BB1_11 Depth=1
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "li	a1, 32",
    "bltu	a0, a1, 81f",
    // in Loop: Header=BB1_11 Depth=1
    // ERRATA BUG2 patch: lbu	a0, 308(s1) (offset=308,bits[4:0]=20)
    "addi s1, s1, -4",
    "lbu a0, 312(s1)",
    "addi s1, s1, 4",
    "sltiu	a0, a0, 62",
    "xori	ra, a0, 1",
    "j	82f",
    "81:", // .LBB1_128: in Loop: Header=BB1_11 Depth=1
    "li	ra, 1",
    "82:", // .LBB1_129: in Loop: Header=BB1_11 Depth=1
    "li	a1, 0",
    "83:", // .LBB1_130: Parent Loop BB1_11 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB1_147 Depth 3
    "slli	a2, a1, 2",
    "beqz	ra, 84f",
    // in Loop: Header=BB1_130 Depth=2
    "add	a3, s1, a2",
    "slli	a4, a1, 1",
    "lw	a0, 80(a3)",
    "mv	a5, s1",
    "lw	s1, 160(a3)",
    "add	a4, a4, a5",
    "lhu	s0, 260(a4)",
    "beqz	s0, 86f",
    // in Loop: Header=BB1_130 Depth=2
    "li	s0, 0",
    "lh	a3, 260(a4)",
    "addi	a3, a3, -1",
    "sh	a3, 260(a4)",
    "lui	s1, %hi(124f)",
    "addi	s1, s1, %lo(124f)",
    "j	85f",
    "84:", // .LBB1_133: in Loop: Header=BB1_130 Depth=2
    "li	s0, 0",
    "85:", // .LBB1_134: in Loop: Header=BB1_130 Depth=2
    "addi	a0, sp, 44",
    "add	a2, a2, a0",
    "addi	a1, a1, 1",
    "sw	s0, 0(a2)",
    "li	a0, 10",
    "bne	a1, a0, 83b",
    "j	97f",
    "86:", // .LBB1_135: in Loop: Header=BB1_130 Depth=2
    "srli	a5, a0, 8",
    "slli	s1, s1, 19",
    "lw	s0, 4(sp)", // 4-byte Folded Reload
    "and	s0, s0, a5",
    "bltz	s1, 87f",
    // in Loop: Header=BB1_130 Depth=2
    "lw	t2, 0(a3)",
    "srli	t0, t2, 8",
    "srli	t1, t2, 16",
    "beqz	s0, 94f",
    // in Loop: Header=BB1_130 Depth=2
    "lhu	a3, 240(a4)",
    "lh	a5, 240(a4)",
    "addi	a5, a5, 1",
    "sh	a5, 240(a4)",
    "lhu	a5, 240(a4)",
    // ERRATA BUG2 patch: srli	s1, a0, 20 (shamt=20)
    "srli s1, a0, 19",
    "srli s1, s1, 1",
    "sltu	a3, a3, s1",
    "bltu	a5, s0, 95f",
    // in Loop: Header=BB1_130 Depth=2
    "lw	a5, 40(sp)", // 4-byte Folded Reload
    "sh	a5, 240(a4)",
    "j	95f",
    "87:", // .LBB1_139: in Loop: Header=BB1_130 Depth=2
    "lhu	a3, 240(a4)",
    "li	a5, 255",
    "bltu	a5, a3, 88f",
    // in Loop: Header=BB1_130 Depth=2
    "li	t2, 0",
    "not	t0, a3",
    "mv	t1, a3",
    "j	91f",
    "88:", // .LBB1_141: in Loop: Header=BB1_130 Depth=2
    "li	t1, 512",
    "mv	t0, a3",
    "bltu	t1, a3, 89f",
    // in Loop: Header=BB1_130 Depth=2
    "li	t0, 512",
    "89:", // .LBB1_143: in Loop: Header=BB1_130 Depth=2
    "not	s1, a3",
    "mv	t2, a3",
    "bltu	a3, t1, 90f",
    // in Loop: Header=BB1_130 Depth=2
    "mv	t2, s1",
    "90:", // .LBB1_145: in Loop: Header=BB1_130 Depth=2
    "sltiu	a5, a3, 512",
    "neg	a5, a5",
    "and	t1, a5, s1",
    "91:", // .LBB1_146: in Loop: Header=BB1_130 Depth=2
    "lh	a5, 280(a4)",
    "addi	a5, a5, 768",
    "sh	a5, 280(a4)",
    "lhu	a5, 280(a4)",
    "bltu	a5, s0, 93f",
    "92:", // .LBB1_147: Parent Loop BB1_11 Depth=1
    // Parent Loop BB1_130 Depth=2
    // =>    This Inner Loop Header: Depth=3
    "lh	a5, 280(a4)",
    "addi	a3, a3, 1",
    "sub	a5, a5, s0",
    "sh	a5, 280(a4)",
    "slli	a5, a3, 16",
    "lhu	s1, 280(a4)",
    "srli	a5, a5, 16",
    "sltiu	a5, a5, 768",
    "neg	a5, a5",
    "and	a3, a3, a5",
    "bgeu	s1, s0, 92b",
    "93:", // .LBB1_148: in Loop: Header=BB1_130 Depth=2
    "sh	a3, 240(a4)",
    "94:", // .LBB1_149: in Loop: Header=BB1_130 Depth=2
    "li	a3, 1",
    "95:", // .LBB1_150: in Loop: Header=BB1_130 Depth=2
    "lui	s1, %hi(124f)",
    "addi	s1, s1, %lo(124f)",
    "li	s0, 0",
    "beqz	a3, 85b",
    // in Loop: Header=BB1_130 Depth=2
    "andi	a3, a0, 255",
    "beqz	a3, 85b",
    // in Loop: Header=BB1_130 Depth=2
    "li	a0, 255",
    "beq	a3, a0, 96f",
    // in Loop: Header=BB1_130 Depth=2
    "andi	a0, t1, 255",
    "addi	a3, a3, 1",
    "andi	a4, t0, 255",
    "andi	a5, t2, 255",
    "mul	a0, a3, a0",
    "mul	a4, a3, a4",
    "mul	a3, a3, a5",
    "srli	t1, a0, 8",
    "srli	t0, a4, 8",
    "srli	t2, a3, 8",
    "96:", // .LBB1_154: in Loop: Header=BB1_130 Depth=2
    "andi	a0, t1, 255",
    "andi	a3, t0, 255",
    "slli	a0, a0, 16",
    "slli	a3, a3, 8",
    "or	a0, a0, a3",
    "andi	s0, t2, 255",
    "or	s0, s0, a0",
    "j	85b",
    "97:", // .LBB1_155: in Loop: Header=BB1_11 Depth=1
    "lbu	a0, 318(s1)",
    "sw	a0, 8(sp)", // 4-byte Folded Spill
    "lui	a0, 8",
    // --- inline asm begin ---
    "mv	x26, a0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, a0",
    // --- inline asm end ---
    "lw	a0, 0(sp)", // 4-byte Folded Reload
    // --- inline asm begin ---
    "mv	x23, a0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "li	a2, 0",
    "98:", // .LBB1_156: Parent Loop BB1_11 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB1_158 Depth 3
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a0, x31",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a1, x31",
    // --- inline asm end ---
    "sub	a1, a1, a0",
    "lw	a0, 12(sp)", // 4-byte Folded Reload
    "and	a0, a0, a1",
    "snez	a0, a0",
    "addi	a0, a0, 1",
    "lw	a1, 8(sp)", // 4-byte Folded Reload
    "bne	a0, a1, 102f",
    // in Loop: Header=BB1_156 Depth=2
    "sw	a2, 20(sp)", // 4-byte Folded Spill
    "slli	a0, a2, 2",
    "addi	a1, sp, 44",
    "add	a0, a0, a1",
    "lw	s0, 0(a0)",
    "li	s1, 24",
    "99:", // .LBB1_158: Parent Loop BB1_11 Depth=1
    // Parent Loop BB1_156 Depth=2
    // =>    This Inner Loop Header: Depth=3
    "slli	a0, s0, 8",
    "bltz	a0, 100f",
    // in Loop: Header=BB1_158 Depth=3
    "jal	ra, 122f",
    "j	101f",
    "100:", // .LBB1_160: in Loop: Header=BB1_158 Depth=3
    "jal	ra, 123f",
    "101:", // .LBB1_161: in Loop: Header=BB1_158 Depth=3
    "addi	s1, s1, -1",
    "slli	s0, s0, 1",
    "bnez	s1, 99b",
    // in Loop: Header=BB1_156 Depth=2
    // ERRATA BUG2 patch: lw	a2, 20(sp) (offset=20,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw a2, 24(sp)",
    "addi sp, sp, 4",
    "addi	a2, a2, 1",
    "lui	s1, %hi(124f)",
    "addi	s1, s1, %lo(124f)",
    "li	a0, 10",
    "bne	a2, a0, 98b",
    // in Loop: Header=BB1_11 Depth=1
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a0, x31",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a1, x31",
    // --- inline asm end ---
    "sub	a1, a1, a0",
    "lw	a0, 12(sp)", // 4-byte Folded Reload
    "and	a0, a0, a1",
    "snez	a0, a0",
    "addi	a0, a0, 1",
    "lw	a1, 8(sp)", // 4-byte Folded Reload
    "beq	a0, a1, 103f",
    // in Loop: Header=BB1_11 Depth=1
    "jal	ra, 114f",
    "lui	a0, 8",
    // --- inline asm begin ---
    "mv	x26, a0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, a0",
    // --- inline asm end ---
    "lw	a0, 0(sp)", // 4-byte Folded Reload
    // --- inline asm begin ---
    "mv	x23, a0",
    // --- inline asm end ---
    "j	103f",
    "102:", // .LBB1_165: in Loop: Header=BB1_11 Depth=1
    "jal	ra, 114f",
    "lui	a0, 8",
    // --- inline asm begin ---
    "mv	x26, a0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, a0",
    // --- inline asm end ---
    "lw	a0, 0(sp)", // 4-byte Folded Reload
    // --- inline asm begin ---
    "mv	x23, a0",
    // --- inline asm end ---
    "103:", // .LBB1_166: in Loop: Header=BB1_11 Depth=1
    "li	a0, 20",
    "sb	a0, 312(s1)",
    "j	76b",
    "104:", // .LBB1_167
    "addi	a0, s1, 416",
    "li	a1, 10",
    "li	t0, 50",
    "105:", // .LBB1_168: =>This Inner Loop Header: Depth=1
    "lw	a3, -80(a0)",
    "srli	a3, a3, 24",
    "bnez	a3, 24b",
    // in Loop: Header=BB1_168 Depth=1
    "lw	a3, -40(a0)",
    "srli	a4, a3, 8",
    // ERRATA BUG2 patch: srli	a3, a3, 20 (shamt=20)
    "srli a3, a3, 19",
    "srli a3, a3, 1",
    "lw	a2, 4(sp)", // 4-byte Folded Reload
    "and	a4, a4, a2",
    "bnez	a3, 106f",
    // in Loop: Header=BB1_168 Depth=1
    "beqz	a4, 107f",
    "106:", // .LBB1_171: in Loop: Header=BB1_168 Depth=1
    "beqz	a4, 24b",
    // in Loop: Header=BB1_168 Depth=1
    "bltu	a4, a3, 24b",
    "107:", // .LBB1_173: in Loop: Header=BB1_168 Depth=1
    "lw	a5, 0(a0)",
    "lw	a3, -40(a0)",
    "srli	a4, a5, 13",
    "bnez	a4, 24b",
    // in Loop: Header=BB1_168 Depth=1
    "srli	a2, a3, 8",
    "srli	s1, a5, 12",
    "lw	a4, 4(sp)", // 4-byte Folded Reload
    "and	a2, a2, a4",
    "bnez	s1, 108f",
    // in Loop: Header=BB1_168 Depth=1
    "and	a3, a5, a4",
    "lui	s1, %hi(124f)",
    "addi	s1, s1, %lo(124f)",
    "beqz	a3, 109f",
    // in Loop: Header=BB1_168 Depth=1
    "beqz	a2, 24b",
    "j	109f",
    "108:", // .LBB1_177: in Loop: Header=BB1_168 Depth=1
    "lui	s1, %hi(124f)",
    "addi	s1, s1, %lo(124f)",
    "bltu	a2, t0, 24b",
    // in Loop: Header=BB1_168 Depth=1
    // ERRATA BUG2 patch: srli	a3, a3, 20 (shamt=20)
    "srli a3, a3, 19",
    "srli a3, a3, 1",
    "bne	a3, a2, 24b",
    "109:", // .LBB1_179: in Loop: Header=BB1_168 Depth=1
    "addi	a1, a1, -1",
    "addi	a0, a0, 4",
    "bnez	a1, 105b",
    "addi	a0, s1, 336",
    "addi	a1, s1, 376",
    "110:", // .LBB1_181: =>This Inner Loop Header: Depth=1
    "lw	a2, 0(a0)",
    "sw	a2, -296(a0)",
    "lw	a2, 40(a0)",
    "sw	a2, -216(a0)",
    "lw	a2, 80(a0)",
    "sw	a2, -136(a0)",
    "addi	a0, a0, 4",
    "bne	a0, a1, 110b",
    "jal	ra, 117f",
    "li	a0, 2000",
    "sh	a0, 316(s1)",
    "j	24b",
    "111:", // abort_v2_frame: @abort_v2_frame
    "lui	a0, %hi(124f)",
    "addi	a0, a0, %lo(124f)",
    // ERRATA BUG2 patch: lbu	a1, 308(a0) (offset=308,bits[4:0]=20)
    "addi a0, a0, -4",
    "lbu a1, 312(a0)",
    "addi a0, a0, 4",
    "li	a2, 32",
    "bltu	a1, a2, 112f",
    // ERRATA BUG2 patch: lbu	a1, 308(a0) (offset=308,bits[4:0]=20)
    "addi a0, a0, -4",
    "lbu a1, 312(a0)",
    "addi a0, a0, 4",
    "li	a2, 61",
    "bltu	a2, a1, 112f",
    "li	a1, -1",
    "sb	a1, 308(a0)",
    "sh	zero, 314(a0)",
    "lbu	a1, 313(a0)",
    "sb	a1, 309(a0)",
    "sb	zero, 312(a0)",
    "lbu	a0, 309(a0)",
    "beqz	a0, 113f",
    "112:", // .LBB2_3
    "ret",
    "113:", // .LBB2_4
    // --- inline asm begin ---
    "mv	x26, a0",
    // --- inline asm end ---
    "ret",
    "114:", // note_quantum_class: @note_quantum_class
    "lui	a1, %hi(124f)",
    "addi	a1, a1, %lo(124f)",
    "lbu	a2, 318(a1)",
    "beqz	a2, 116f",
    "lbu	a2, 318(a1)",
    "beq	a2, a0, 115f",
    "sb	a0, 318(a1)",
    "li	a0, 100",
    "sb	a0, 310(a1)",
    "lui	a0, 8",
    "lui	a1, 1048568",
    // --- inline asm begin ---
    "mv	x26, a0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, a0",
    // --- inline asm end ---
    "addi	a1, a1, -1",
    // --- inline asm begin ---
    "mv	x23, a1",
    // --- inline asm end ---
    "115:", // .LBB3_3
    "ret",
    "116:", // .LBB3_4
    "sb	a0, 318(a1)",
    "lbu	a0, 310(a1)",
    "li	a2, 99",
    "bltu	a2, a0, 115b",
    "li	a0, 100",
    "sb	a0, 310(a1)",
    "ret",
    "117:", // commit_frame: @commit_frame
    "lui	a0, %hi(124f)",
    "addi	a0, a0, %lo(124f)",
    "lbu	a1, 309(a0)",
    "addi	a2, a0, 240",
    "addi	a3, a0, 200",
    "addi	a4, a0, 260",
    "118:", // .LBB4_1: =>This Inner Loop Header: Depth=1
    "lw	a5, -160(a3)",
    "sw	a5, -200(a3)",
    "lw	a5, -80(a3)",
    "sw	a5, -120(a3)",
    "lw	a5, 0(a3)",
    "sw	a5, -40(a3)",
    "lw	a5, 0(a3)",
    "sh	zero, 0(a2)",
    // ERRATA BUG2 patch: slli	a5, a5, 20 (shamt=20)
    "slli a5, a5, 19",
    "slli a5, a5, 1",
    // ERRATA BUG2 patch: srli	a5, a5, 20 (shamt=20)
    "srli a5, a5, 19",
    "srli a5, a5, 1",
    "sh	a5, 20(a2)",
    "sh	zero, 40(a2)",
    "addi	a2, a2, 2",
    "addi	a3, a3, 4",
    "bne	a2, a4, 118b",
    "li	a2, 1",
    "sb	a2, 309(a0)",
    "bnez	a1, 119f",
    "li	a1, 100",
    "sb	a1, 310(a0)",
    "119:", // .LBB4_4
    "sb	zero, 311(a0)",
    "sb	zero, 312(a0)",
    "ret",
    "120:", // commit_pixel: @commit_pixel
    "lui	a2, %hi(124f)",
    "addi	a2, a2, %lo(124f)",
    "lbu	a3, 309(a2)",
    "lw	a4, 300(a2)",
    "slli	a5, a0, 2",
    "add	a5, a5, a2",
    "sw	a4, 0(a5)",
    "lw	a4, 304(a2)",
    "slli	a0, a0, 1",
    "sw	a4, 80(a5)",
    // ERRATA BUG2 patch: slli	a4, a1, 20 (shamt=20)
    "slli a4, a1, 19",
    "slli a4, a4, 1",
    "sw	a1, 160(a5)",
    "li	a1, 1",
    "add	a0, a0, a2",
    // ERRATA BUG2 patch: srli	a4, a4, 20 (shamt=20)
    "srli a4, a4, 19",
    "srli a4, a4, 1",
    "sh	zero, 240(a0)",
    "sh	a4, 260(a0)",
    "sh	zero, 280(a0)",
    "sb	a1, 309(a2)",
    "bnez	a3, 121f",
    "li	a0, 100",
    "sb	a0, 310(a2)",
    "121:", // .LBB5_2
    "sb	zero, 311(a2)",
    "sb	zero, 312(a2)",
    "ret",
    "122:", // send_quantum_zero: @send_quantum_zero
    "lui	a0, 1048568",
    "addi	a0, a0, -1",
    "lui	a1, 8",
    // --- inline asm begin ---
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x22, a1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "ret",
    "123:", // send_quantum_one: @send_quantum_one
    "lui	a0, 1048568",
    "addi	a0, a0, -1",
    "lui	a1, 8",
    // --- inline asm begin ---
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x22, a1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "ret",
    // --- rodata: controller (438 entries, 116 words) ---
    ".p2align 2",
    "124:", // controller
    ".word 0x00000000", // [0] 0, 0, 0, 0
    ".word 0x00000000", // [4] 0, 0, 0, 0
    ".word 0x00000000", // [8] 0, 0, 0, 0
    ".word 0x00000000", // [12] 0, 0, 0, 0
    ".word 0x00000000", // [16] 0, 0, 0, 0
    ".word 0x00000000", // [20] 0, 0, 0, 0
    ".word 0x00000000", // [24] 0, 0, 0, 0
    ".word 0x00000000", // [28] 0, 0, 0, 0
    ".word 0x00000000", // [32] 0, 0, 0, 0
    ".word 0x00000000", // [36] 0, 0, 0, 0
    ".word 0x00000000", // [40] 0, 0, 0, 0
    ".word 0x00000000", // [44] 0, 0, 0, 0
    ".word 0x00000000", // [48] 0, 0, 0, 0
    ".word 0x00000000", // [52] 0, 0, 0, 0
    ".word 0x00000000", // [56] 0, 0, 0, 0
    ".word 0x00000000", // [60] 0, 0, 0, 0
    ".word 0x00000000", // [64] 0, 0, 0, 0
    ".word 0x00000000", // [68] 0, 0, 0, 0
    ".word 0x00000000", // [72] 0, 0, 0, 0
    ".word 0x00000000", // [76] 0, 0, 0, 0
    ".word 0x00000000", // [80] 0, 0, 0, 0
    ".word 0x00000000", // [84] 0, 0, 0, 0
    ".word 0x00000000", // [88] 0, 0, 0, 0
    ".word 0x00000000", // [92] 0, 0, 0, 0
    ".word 0x00000000", // [96] 0, 0, 0, 0
    ".word 0x00000000", // [100] 0, 0, 0, 0
    ".word 0x00000000", // [104] 0, 0, 0, 0
    ".word 0x00000000", // [108] 0, 0, 0, 0
    ".word 0x00000000", // [112] 0, 0, 0, 0
    ".word 0x00000000", // [116] 0, 0, 0, 0
    ".word 0x00000000", // [120] 0, 0, 0, 0
    ".word 0x00000000", // [124] 0, 0, 0, 0
    ".word 0x00000000", // [128] 0, 0, 0, 0
    ".word 0x00000000", // [132] 0, 0, 0, 0
    ".word 0x00000000", // [136] 0, 0, 0, 0
    ".word 0x00000000", // [140] 0, 0, 0, 0
    ".word 0x00000000", // [144] 0, 0, 0, 0
    ".word 0x00000000", // [148] 0, 0, 0, 0
    ".word 0x00000000", // [152] 0, 0, 0, 0
    ".word 0x00000000", // [156] 0, 0, 0, 0
    ".word 0x00000000", // [160] 0, 0, 0, 0
    ".word 0x00000000", // [164] 0, 0, 0, 0
    ".word 0x00000000", // [168] 0, 0, 0, 0
    ".word 0x00000000", // [172] 0, 0, 0, 0
    ".word 0x00000000", // [176] 0, 0, 0, 0
    ".word 0x00000000", // [180] 0, 0, 0, 0
    ".word 0x00000000", // [184] 0, 0, 0, 0
    ".word 0x00000000", // [188] 0, 0, 0, 0
    ".word 0x00000000", // [192] 0, 0, 0, 0
    ".word 0x00000000", // [196] 0, 0, 0, 0
    ".word 0x00000000", // [200] 0, 0, 0, 0
    ".word 0x00000000", // [204] 0, 0, 0, 0
    ".word 0x00000000", // [208] 0, 0, 0, 0
    ".word 0x00000000", // [212] 0, 0, 0, 0
    ".word 0x00000000", // [216] 0, 0, 0, 0
    ".word 0x00000000", // [220] 0, 0, 0, 0
    ".word 0x00000000", // [224] 0, 0, 0, 0
    ".word 0x00000000", // [228] 0, 0, 0, 0
    ".word 0x00000000", // [232] 0, 0, 0, 0
    ".word 0x00000000", // [236] 0, 0, 0, 0
    ".word 0x00000000", // [240] 0, 0, 0, 0
    ".word 0x00000000", // [244] 0, 0, 0, 0
    ".word 0x00000000", // [248] 0, 0, 0, 0
    ".word 0x00000000", // [252] 0, 0, 0, 0
    ".word 0x00000000", // [256] 0, 0, 0, 0
    ".word 0x00000000", // [260] 0, 0, 0, 0
    ".word 0x00000000", // [264] 0, 0, 0, 0
    ".word 0x00000000", // [268] 0, 0, 0, 0
    ".word 0x00000000", // [272] 0, 0, 0, 0
    ".word 0x00000000", // [276] 0, 0, 0, 0
    ".word 0x00000000", // [280] 0, 0, 0, 0
    ".word 0x00000000", // [284] 0, 0, 0, 0
    ".word 0x00000000", // [288] 0, 0, 0, 0
    ".word 0x00000000", // [292] 0, 0, 0, 0
    ".word 0x00000000", // [296] 0, 0, 0, 0
    ".word 0x00000000", // [300] 0, 0, 0, 0
    ".word 0x00000000", // [304] 0, 0, 0, 0
    ".word 0x00000000", // [308] 0, 0, 0, 0
    ".word 0x00000000", // [312] 1110717252, 827608911, 65566, 0
    ".word 0x00000000", // [316] 0, 0, 0, 0
    ".word 0x42343344", // [320] 0, 0, 0, 0
    ".word 0x31544f4f", // [324] 0, 0, 0, 0
    ".word 0x0001001e", // [328] 0, 0, 0, 0
    ".word 0x00000000", // [332] 0, 0, 0, 0
    ".word 0x00000000", // [336] 0, 0, 0, 0
    ".word 0x00000000", // [340] 0, 0, 0, 0
    ".word 0x00000000", // [344] 0, 0, 0, 0
    ".word 0x00000000", // [348] 0, 0, 0, 0
    ".word 0x00000000", // [352] 0, 0, 0, 0
    ".word 0x00000000", // [356] 0, 0, 0, 0
    ".word 0x00000000", // [360] 0, 0, 0, 0
    ".word 0x00000000", // [364] 0, 0, 0, 0
    ".word 0x00000000", // [368] 0, 0, 0, 0
    ".word 0x00000000", // [372] 0, 0, 0, 0
    ".word 0x00000000", // [376] 0, 0, 0, 0
    ".word 0x00000000", // [380] 0, 0, 0, 0
    ".word 0x00000000", // [384] 0, 0, 0, 0
    ".word 0x00000000", // [388] 0, 0, 0, 0
    ".word 0x00000000", // [392] 0, 0, 0, 0
    ".word 0x00000000", // [396] 0, 0, 0, 0
    ".word 0x00000000", // [400] 0, 0, 0, 0
    ".word 0x00000000", // [404] 0, 0, 0, 0
    ".word 0x00000000", // [408] 0, 0, 0, 0
    ".word 0x00000000", // [412] 0, 0, 0, 0
    ".word 0x00000000", // [416] 0, 0, 0, 0
    ".word 0x00000000", // [420] 0, 0, 0, 0
    ".word 0x00000000", // [424] 0, 0, 0, 0
    ".word 0x00000000", // [428] 0, 0, 0, 0
    ".word 0x00000000", // [432] 0, 0, 0, 0
    ".word 0x00000000", // [436] 4133823751, 558124613
    ".word 0x00000000", // [440]
    ".word 0x00000000", // [444]
    ".word 0x00000000", // [448]
    ".word 0x00000000", // [452]
    ".word 0xf6652507", // [456]
    ".word 0x21444e45" // [460]
);
